version: 2
updates:
- package-ecosystem: nuget
  directory: "/src/MediaFileManager/PackageProject"
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
- package-ecosystem: nuget
  directory: "/src/MediaFileManager/MediaFileManager.Desktop"
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
