using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MediaFileManager.Desktop.Views.VideoFilesView.UpdateFileNameButton_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MediaFileManager.Desktop.Views.VideoFilesView.SelectFolderButton_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MediaFileManager.Desktop.Views.VideoFilesView.RenumberWorker_DoWork(System.Object,System.ComponentModel.DoWorkEventArgs)")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MediaFileManager.Desktop.Views.AudiobookFilesView.BackgroundWorker_DoWork(System.Object,System.ComponentModel.DoWorkEventArgs)")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MediaFileManager.Desktop.Views.AudiobookFilesView.SelectAuthorFolderButton_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Design", "CA1001:Types that own disposable fields should be disposable", Justification = "<Pending>", Scope = "type", Target = "~T:MediaFileManager.Desktop.Views.AudiobookFilesView")]
[assembly: SuppressMessage("Design", "CA1001:Types that own disposable fields should be disposable", Justification = "<Pending>", Scope = "type", Target = "~T:MediaFileManager.Desktop.Views.VideoFilesView")]
