name:  WPF CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
      CERTIFICATE_FILENAME: LancelotSoftwareLLC.pfx
      TELERIK_USERNAME: ${{ secrets.TELERIK_USERNAME }}
      TELERIK_PASSWORD: ${{ secrets.TELERIK_PASSWORD }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoids shallow clone if using actions/checkout@v2 (required for nbgv)
    
    # Install the .NET Core workload
    - name: Install .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    # Add  MsBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.0

    - uses: Amadevus/pwsh-script@v1
      id: version-creator
      with:
        script: |
          $buildDay = Get-Date -Format "yyyy.Mdd"
          $version = $buildDay + "." + $env:GITHUB_RUN_NUMBER + ".0"
          echo $version
          return $version

    # Update the UWP package version
    - name: Update manifest version
      run: |
        [xml]$manifest = get-content "src\MediaFileManager\PackageProject\Package.appxmanifest"
        $manifest.Package.Identity.Version = "${{ steps.version-creator.outputs.result }}"
        $manifest.save("src\MediaFileManager\PackageProject\Package.appxmanifest")

    - name: NuGet Restore
      run: dotnet restore src\MediaFileManager\MediaFileManager.sln --configfile src\nuget.config --runtime $env:RID
      env:
        # https://docs.microsoft.com/en-us/dotnet/core/rid-catalog
        RID: win-x86

    # Restore WPF project
    - name: Restore the Wpf application to populate the obj folder
      run: msbuild src\MediaFileManager\MediaFileManager.Desktop\MediaFileManager.Desktop.csproj /t:Restore /p:Configuration=Debug /p:RuntimeIdentifier=$env:RID
      env:
        # https://docs.microsoft.com/en-us/dotnet/core/rid-catalog
        RID: win-x86

    # Decode the Base64 encoded certificate, save it as a PFX file and install it
    - name: Decode and Install the Signing Certificate
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.LancelotSoftwareCert_Base64 }}")
        $currentDirectory = Get-Location
        $certificatePath = Join-Path -Path $currentDirectory -ChildPath src\MediaFileManager\PackageProject -AdditionalChildPath $env:CERTIFICATE_FILENAME
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)

    # Build the WAP project
    - name: Build the Windows Application Packaging Project (wapproj) 
      run: msbuild src\MediaFileManager\MediaFileManager.sln /p:Platform=$env:TargetPlatform /p:Configuration=$env:Configuration /p:UapAppxPackageBuildMode=$env:BuildMode /p:AppxBundle=$env:AppxBundle /p:PackageCertificateThumbprint=${{ secrets.LancelotSoftwareCert_Thumbprint }} /p:PackageCertificateKeyFile=$env:CERTIFICATE_FILENAME /p:PackageCertificatePassword=${{ secrets.LancelotSoftwareCert_Key }}
      env:
        AppxBundle: Never
        BuildMode: SideLoadOnly
        Configuration: Debug
        TargetPlatform: x86

    # Delete the .pfx
    - name: Uninstall the Signing Certificate
      run: Remove-Item -path src\MediaFileManager\PackageProject\$env:CERTIFICATE_FILENAME

    # Upload the MSIX package: https://github.com/marketplace/actions/upload-artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: MSIX Package
        path: src\MediaFileManager\PackageProject\AppPackages\
